[book]
title = "Violet documentation"
author = "Gulce"
description = "Future â€” Powered by Violet, designed for You."
src = "docs"
language = "en"
theme = "rust"

[rust]
edition = "2018"

[build]
build-dir = "book"

[output.html]
git-repository-url="https://github.com/violet-eco/docs"
site-url="https://violet-eco.github.io/docs"
